# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: pr
on:
  pull_request:
    branches:
      - main

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - run: dotnet build -c Release

      - run: dotnet run -c Release --no-build
        working-directory: Optify.Tests
